In [21]:
from notebook.services.config import ConfigManager
cm = ConfigManager()
cm.update('livereveal', {
              'width': 1000,
              'height': 600,
              'scroll': True,
})

{'height': 600, 'scroll': True, 'width': 1000}

# NumPy

Álgebra linear é um ramo da matemática muito utilizado em Ciências de Dados, principalmente em *Machine Learning*. Sua representação contínua faz-se muito útil para o campo. 

Utilizando Python, temos o pacote Numpy, que consegue aplicar os conceitos de álgebra facilmente, de forma a facilitar a vida do desenvolvedor da área. o principal objeto do Numpy são os arrays multidimensionais, que podem ser criados através da função ndarray. 

Para cada conceito apresentado neste tutorial, serão apresentados alguns exemplos em Numpy.

[Documentação em inglês do NumPy](https://docs.scipy.org/doc/numpy-1.14.0/reference/index.html)

[Guia do usuário NumPy, em inglês](https://docs.scipy.org/doc/numpy-1.14.0/user/index.html)

[Documentação do pyscience-brasil, em português](http://pyscience-brasil.wikidot.com/module:numpy#toc2)

In [22]:
import numpy as np

## Tipos de objetos em Álgebra

### Escalares

[Escalares](https://docs.scipy.org/doc/numpy/reference/arrays.scalars.html) são apenas números. Geralmente são utilizados para aplicar transformações a Vetores e Matrizes

### Vetores
É um arranjo ordenado de números. Pode-se identificar cada número individual por seu indíce. 

### Matrizes
São arranjos bidimensionais de números. Cada elemento é identificado por dois indíces, diferente dos vetores. 

### Tensores
Em alguns casos é necessário um arranjo com mais de dois eixos. É representado por uma grade e com número variável de eixos. 

In [23]:
# Escalar em python
a = 1
b = 2.5
c = 1/4

# Vetores
vetor = np.array([1, 2, 3, 4, 5])
print("Vetor \n {}\n".format(vetor))

# Matrizes
matriz = np.array([[4, 5, 6],[9, 8, 7]])
print("Matriz \n {}\n".format(matriz))

# Tensores
tensor = np.array([[1,2,3], [4,5,6],[7,8,9]])
print("Tensor \n {}\n".format(tensor))

Vetor 
 [1 2 3 4 5]

Matriz 
 [[4 5 6]
 [9 8 7]]

Tensor 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Propriedades do vetor: Tamanho: 5, Dimensão(5,)
Propriedades da matriz: Tamanho: 6, Dimensão(2, 3)
Propriedades do tensor: Tamanho: 9, Dimensão(3, 3)


## Criação de arranjos (arrays)

Existem diversas maneiras de se criar arrays e cada uma delas possui um propósito específico. Abaixo segue a documentção em 

[Routinas para criação de arrays](https://docs.scipy.org/doc/numpy-1.14.0/reference/routines.array-creation.html)

### Usando sequência
[Documentação do Numpy arange](https://docs.scipy.org/doc/numpy-.14.0/reference/generated/numpy.arange.html)

### Vetores aleatórios
[Funções diversas para geração de vetores aleatórios](https://docs.scipy.org/doc/numpy/reference/routines.random.html)

### Vetor de zeros, uns e vazios
[Gerador de arrays de zeros](https://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros.html#numpy.zeros)

[Gerador de arrays de uns](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html#numpy.ones)

[Vazios](https://docs.scipy.org/doc/numpy/reference/generated/numpy.empty_like.html#numpy.empty)

Gerar arrays com base em arrays existentes

[Zeros like](https://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros_like.html#numpy.zeros_like)

[Uns Like](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ones_like.html#numpy.ones_like)

[Vazios like](https://docs.scipy.org/doc/numpy/reference/generated/numpy.empty_like.html#numpy.empty_like)


In [24]:
# Usando sequência
np.arange(10)

# Vetores aleatorios
# gerando uma semente para os pseudo aleatórios
np.random.seed(12345)

# Vetores aleatórios de um determinado formato

matriz_2_2 = np.random.rand(2,2)

print("Matriz aleatória 2x2\n {} \n".format(matriz_2_2))

Matriz aleatória 2x2
 [[0.92961609 0.31637555]
 [0.18391881 0.20456028]] 



In [25]:
# Retorna um vetor de inteiros entre menor e maior, excluindo maior

vetor_aleatorio = np.random.randint(low=0, high=10, size=5)

print("Vetor de inteiros aleatório entre 0 e 10, de tamanho 5\n {}\n".format(vetor_aleatorio))

Vetor de inteiros aleatório entre 0 e 10, de tamanho 5
 [5 2 1 6 1]



In [26]:
# Retorna um vetor de números flutuantes

tensor_flut = np.random.random((3,4,2))

print("Tensor aleatório de dimensões 3x4x2 \n {}\n".format(tensor_flut))

Tensor aleatório de dimensões 3x4x2 
 [[[0.6531771  0.74890664]
  [0.65356987 0.74771481]
  [0.96130674 0.0083883 ]
  [0.10644438 0.29870371]]

 [[0.65641118 0.80981255]
  [0.87217591 0.9646476 ]
  [0.72368535 0.64247533]
  [0.71745362 0.46759901]]

 [[0.32558468 0.43964461]
  [0.72968908 0.99401459]
  [0.67687371 0.79082252]
  [0.17091426 0.02684928]]]



In [27]:
# Cria um vetor de zeros com determinado formato
vetor_zeros = np.zeros((5,2))
print("Matriz de zeros, dimensões 5x2 \n{}\n ".format(vetor_zeros))

Matriz de zeros, dimensões 5x2 
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
 


In [28]:
# Cria um vetor de uns com determinado formato
matriz_uns = np.ones((4,3))
print("Matriz de Uns, dimensões 4x3 \n{}\n".format(matriz_uns))

Matriz de Uns, dimensões 4x3 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]



In [29]:
# Cria um vetor vazio com um determinado formato
tensor_vazio = np.empty((3,4,2))
print("Tensor vazio, dimensões 3x4x2 \n{}\n".format(tensor_vazio))

Tensor vazio, dimensões 3x4x2 
[[[0.6531771  0.74890664]
  [0.65356987 0.74771481]
  [0.96130674 0.0083883 ]
  [0.10644438 0.29870371]]

 [[0.65641118 0.80981255]
  [0.87217591 0.9646476 ]
  [0.72368535 0.64247533]
  [0.71745362 0.46759901]]

 [[0.32558468 0.43964461]
  [0.72968908 0.99401459]
  [0.67687371 0.79082252]
  [0.17091426 0.02684928]]]



In [30]:
# Criando vetores com base em vetores existentes
print("Vetor de zeros como modelo \n {}".format(np.zeros_like(vetor)))
print("Matriz de uns como modelo \n {}".format(np.ones_like(matriz)))
print("Tensor de vazio como modelo \n {}".format(np.empty_like(tensor)))

Vetor de zeros como modelo 
 [0 0 0 0 0]
Matriz de uns como modelo 
 [[1 1 1]
 [1 1 1]]
Tensor de vazio como modelo 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


## Operações
## Indices, fatiamento(slices) e iteração

In [31]:
vetor_rand=np.random.randint(0,10,10)
# Seleção de intervalos
# Selecionando intervalo máximo excluindo valor no indice máximo
print("Selecionando limite superior:\n {}\n".format(vetor_rand[:5]))

# Selecionando intervalo com mínimo
print("Selecionando limite inferior: \n{}\n".format(vetor_rand[5:]))

# Selecionando uma faixa 
print("Selecionando uma intervalo: \n{}\n".format(vetor_rand[3:8]))

# Selecionando um passo de avanço
print("Avançando com passo 2: \n{}\n".format(vetor_rand[::2]))

# Inversão
print("Invertendo o vetor: \n{}\n".format(vetor_rand[:-1]))

Selecionando limite superior:
 [5 3 0 6 8]

Selecionando limite inferior: 
[0 5 6 8 9]

Selecionando uma intervalo: 
[6 8 0 5 6]

Avançando com passo 2: 
[5 0 8 5 8]

Invertendo o vetor: 
[5 3 0 6 8 0 5 6 8]



In [32]:
# Iteração sobre vetores


In [33]:
# Iteração sobre matrizes

In [34]:
# Iteração sobre tensores

## Redimensionamento de arrays

In [35]:
# Obtendo as formas
# Propriedades Tamanho e dimensões
print("Propriedades do vetor: Tamanho: {}, Dimensão{}".format(vetor.size, vetor.shape))
print("Propriedades da matriz: Tamanho: {}, Dimensão{}".format(matriz.size, matriz.shape))
print("Propriedades do tensor: Tamanho: {}, Dimensão{}".format(tensor.size, tensor.shape))

In [49]:
# Planificando uma matriz ou tensor
print("Matriz planificada: \n {} \n".format(matriz.ravel()))
print("Tensor planificado: \n {} \n".format(tensor.ravel()))

Matriz planificada: 
 [4 5 6 9 8 7] 

Tensor planificado: 
 [1 2 3 4 5 6 7 8 9] 



In [61]:
# Reshape, não modifica o array original, apenas retorna o novo formato
print("Modificando a forma da matriz \n{}\n".format(matriz.reshape(2,3)))
print("Matriz original \n{}\n".format(matriz))

Modificando a forma da matriz 
[[4 5 6]
 [9 8 7]]

Matriz original 
[[4 5]
 [6 9]
 [8 7]]

Usando reshape, o retorno é None
None

Mas a mudança foi feita na matriz em si
[[4 5]
 [6 9]
 [8 7]]
 


In [ ]:
# Resize modifica o array em si mesmo
print("Usando reshape, o retorno é None\n{}\n".format(matriz.resize((3,2))))
print("Mas a mudança foi feita na matriz em si\n{}\n ".format(matriz))

## Broadcasting ou propagação

Estes termos são utilizados para descrever como o NumPy trata operações aritméticas com arrays de formas diferentes. O array menor propaga sobre o maior, caso eles tenham dimensões compatíveis.


### Regras gerais de propagação

Quando for realizar operações com dois arrays, NumPy compara os as dimensões elemento a elemento. Começando pela dimensão mais ao final.
Duas dimensões são compatíveis quando

1. Elas são iguais, ou
2. Uma delas é 1

OU seja, exemplificando em termos de dimensões temos que a propagação funciona em sistemas com dimensões como no exmplo abaixo:
    5 x 1 e 1
    3 x 2 e 2
4 x 2 x 3 e 1
4 x 2 x 3 e 3
4 x 2 x 3 e 4 x 1 x 1
4 x 2 x 3 e 4 x 1 x 3

E por aí vai. Confuso não?! Nos exemplos espero deixar um pouco mais claro.

[Documentação aqui](https://docs.scipy.org/doc/numpy-1.10.1/user/basics.broadcasting.html)

[Ilustração dos conceitos de Broadcast(em inglês)](http://scipy.github.io/old-wiki/pages/EricsBroadcastingDoc)

In [37]:
# Exemplos de broadcast
np.random.randint(0,100,size=20).reshape(5,4)

array([[18, 50, 82, 57],
       [46, 58, 23, 21],
       [ 7, 81, 63,  0],
       [90, 44, 57, 14],
       [26, 43, 30, 99]])

### Transposição de matrizes

Transposição de uma matriz consiste em uma matriz espelho da original, através da diagonal principal. A transposta é obitida trocando-se a posição das linhas e colunas. Denota-se a tranposta da matriz **A** por **A^T**

[Função transpose do Numpy](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.transpose.html)

In [39]:
print("Matriz \n {}".format(matriz))
print("Matriz Transposta \n {}".format(np.transpose(matriz)))

Matriz 
 [[4 5 6]
 [9 8 7]]
Matriz Transposta 
 [[4 9]
 [5 8]
 [6 7]]
Tensor 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Tensor Transposto, usando a forma simplificada 
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
print("Tensor \n {}".format(tensor))
print("Tensor Transposto, usando a forma simplificada \n {}".format(tensor.T))

### Soma e subtração 


In [22]:
# Operação com escalares
# Aplica o conceito de propagação
print("Multiplicando o vetor por 3: \n{}\n".format(vetor * 3))
print("Somando 10 a matriz: \n {} \n".format(matriz + 10))
print("Dividindo o tensor por 5: \n {} \n".format(tensor / 5))

Multiplicando o vetor por 3: 
[ 3  6  9 12 15]

Somando 10 a matriz: 
 [[14 15 16]
 [19 18 17]] 

Dividindo o tensor por 5: 
 [[0.2 0.4 0.6]
 [0.8 1.  1.2]
 [1.4 1.6 1.8]] 



In [43]:
# Usando arrays de mesmo tamanho
vetor1 = np.array([1,2,3,4,5])
vetor2 = np.array([6,3,2,7,8])
print(np.add(vetor1, vetor2))
print(vetor1 + vetor2)


array([-5, -1,  1, -3, -3])

In [ ]:
print(np.subtract(vetor1, vetor2))
print(vetor1 - vetor2)

In [67]:
# Usando arrays de tamanhos diferentes
matriz1 = np.arange(10).reshape(2,5)
vetor_uns = np.ones(5)
matriz1 + vetor_uns

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

(20,)

### Multiplicação de matrizes e vetores

In [ ]:
# Usando arrays de mesmo tamanho
print(np.mul(vetor1, vetor2))
print(vetor1 * vetor2)

In [ ]:
print(np.divide(vetor1, vetor2))
print(vetor1 // vetor2)

In [ ]:
# Usando arrays de tamanhos diferentes

### Matriz identidade e Matriz inversa

### Dependência Linear

### Norma ou módulo

## Tipos especiais de matrizes e vetores

### Unitário
### Diagnonal
### Simétrico
### Ortogonal



## Trabalhando com cópias e visões (views)

## Referências

### Em Português

1. https://pt.khanacademy.org/math/linear-algebra
2. https://www.youtube.com/watch?v=pbFZW1eTnkk

### Em Inglês

1. http://www.deeplearningbook.org/contents/linear_algebra.html
2. https://www.analyticsvidhya.com/blog/2017/05/comprehensive-guide-to-linear-algebra/
3. https://towardsdatascience.com/boost-your-data-sciences-skills-learn-linear-algebra-2c30fdd008cf
