In [1]:
from notebook.services.config import ConfigManager
cm = ConfigManager()
cm.update('livereveal', {
              'width': 1000,
              'height': 600,
              'scroll': True,
})

{'height': 600, 'scroll': True, 'width': 1000}

# NumPy

## Um pouco de álgebra linear

Álgebra linear é um ramo da matemática muito utilizado em Ciências de Dados, principalmente em *Machine Learning*. Sua representação contínua faz-se muito útil para o campo. 

Utilizando Python, temos o pacote Numpy, que consegue aplicar os conceitos de álgebra facilmente, de forma a facilitar a vida do desenvolvedor da área. o principal objeto do Numpy são os arrays multidimensionais, que podem ser criados através da função ndarray. 

Para cada conceito apresentado neste tutorial, serão apresentados alguns exemplos em Numpy.

[Documentação em inglês do NumPy](https://docs.scipy.org/doc/numpy-1.14.0/reference/index.html)

[Guia do usuário NumPy, em inglês](https://docs.scipy.org/doc/numpy-1.14.0/user/index.html)

[Documentação do pyscience-brasil, em português](http://pyscience-brasil.wikidot.com/module:numpy#toc2)

In [2]:
import numpy as np

## Tipos de objetos em Álgebra

### Escalares

[Escalares](https://docs.scipy.org/doc/numpy/reference/arrays.scalars.html) são apenas números. Geralmente são utilizados para aplicar transformações a Vetores e Matrizes

### Vetores
É um arranjo ordenado de números. Pode-se identificar cada número individual por seu indíce. 

### Matrizes
São arranjos bidimensionais de números. Cada elemento é identificado por dois indíces, diferente dos vetores. 

### Tensores
Em alguns casos é necessário um arranjo com mais de dois eixos. É representado por uma grade e com número variável de eixos. 

In [3]:
# Escalar em python
a = 1
b = 2.5
c = 1/4

# Vetores
vetor = np.array([1, 2, 3, 4, 5])
print("Vetor \n {}\n".format(vetor))

# Matrizes
matriz = np.array([[4, 5, 6],[9, 8, 7]])
print("Matriz \n {}\n".format(matriz))

# Tensores
tensor = np.array([[1,2,3], [4,5,6],[7,8,9]])
print("Tensor \n {}\n".format(tensor))

Vetor 
 [1 2 3 4 5]

Matriz 
 [[4 5 6]
 [9 8 7]]

Tensor 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]



## Criação de arranjos (arrays)

Existem diversas maneiras de se criar arrays e cada uma delas possui um propósito específico. Abaixo segue a documentção em 

[Routinas para criação de arrays](https://docs.scipy.org/doc/numpy-1.14.0/reference/routines.array-creation.html)

### Usando sequência
[Documentação do Numpy arange](https://docs.scipy.org/doc/numpy-.14.0/reference/generated/numpy.arange.html)


In [4]:
# Usando sequência
np.arange(10)

# Vetores aleatorios
# gerando uma semente para os pseudo aleatórios
np.random.seed(12345)

# Vetores aleatórios de um determinado formato

matriz_2_2 = np.random.rand(2,2)

print("Matriz aleatória 2x2\n {} \n".format(matriz_2_2))

Matriz aleatória 2x2
 [[0.92961609 0.31637555]
 [0.18391881 0.20456028]] 



### Vetores aleatórios
[Funções diversas para geração de vetores aleatórios](https://docs.scipy.org/doc/numpy/reference/routines.random.html)

In [5]:
# Retorna um vetor de inteiros entre menor e maior, excluindo maior

vetor_aleatorio = np.random.randint(low=0, high=10, size=5)

print("Vetor de inteiros aleatório entre 0 e 10, de tamanho 5\n {}\n".format(vetor_aleatorio))

Vetor de inteiros aleatório entre 0 e 10, de tamanho 5
 [5 2 1 6 1]



In [6]:
# Retorna um vetor de números flutuantes

tensor_flut = np.random.random((3,4,2))

print("Tensor aleatório de dimensões 3x4x2 \n {}\n".format(tensor_flut))

Tensor aleatório de dimensões 3x4x2 
 [[[0.6531771  0.74890664]
  [0.65356987 0.74771481]
  [0.96130674 0.0083883 ]
  [0.10644438 0.29870371]]

 [[0.65641118 0.80981255]
  [0.87217591 0.9646476 ]
  [0.72368535 0.64247533]
  [0.71745362 0.46759901]]

 [[0.32558468 0.43964461]
  [0.72968908 0.99401459]
  [0.67687371 0.79082252]
  [0.17091426 0.02684928]]]



### Vetor de zeros, uns e vazios
[Gerador de arrays de zeros](https://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros.html#numpy.zeros)

[Gerador de arrays de uns](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html#numpy.ones)

[Vazios](https://docs.scipy.org/doc/numpy/reference/generated/numpy.empty_like.html#numpy.empty)

In [7]:
# Cria um vetor de zeros com determinado formato
vetor_zeros = np.zeros((5,2))
print("Matriz de zeros, dimensões 5x2 \n{}\n ".format(vetor_zeros))

Matriz de zeros, dimensões 5x2 
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
 


### Gerar arrays om base em arrays existentes

[Zeros like](https://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros_like.html#numpy.zeros_like)

[Uns Like](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ones_like.html#numpy.ones_like)

[Vazios like](https://docs.scipy.org/doc/numpy/reference/generated/numpy.empty_like.html#numpy.empty_like)

In [8]:
# Cria um vetor de uns com determinado formato
matriz_uns = np.ones((4,3))
print("Matriz de Uns, dimensões 4x3 \n{}\n".format(matriz_uns))

Matriz de Uns, dimensões 4x3 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]



In [9]:
# Cria um vetor vazio com um determinado formato
tensor_vazio = np.empty((3,4,2))
print("Tensor vazio, dimensões 3x4x2 \n{}\n".format(tensor_vazio))

Tensor vazio, dimensões 3x4x2 
[[[0.6531771  0.74890664]
  [0.65356987 0.74771481]
  [0.96130674 0.0083883 ]
  [0.10644438 0.29870371]]

 [[0.65641118 0.80981255]
  [0.87217591 0.9646476 ]
  [0.72368535 0.64247533]
  [0.71745362 0.46759901]]

 [[0.32558468 0.43964461]
  [0.72968908 0.99401459]
  [0.67687371 0.79082252]
  [0.17091426 0.02684928]]]



In [10]:
# Criando vetores com base em vetores existentes
print("Vetor de zeros como modelo \n {}".format(np.zeros_like(vetor)))
print("Matriz de uns como modelo \n {}".format(np.ones_like(matriz)))
print("Tensor de vazio como modelo \n {}".format(np.empty_like(tensor)))

Vetor de zeros como modelo 
 [0 0 0 0 0]
Matriz de uns como modelo 
 [[1 1 1]
 [1 1 1]]
Tensor de vazio como modelo 
 [[              0 139624158125992 139624351602928]
 [139624292491368 139624299337520 139623750358104]
 [ 94252534120096  94252534120352              80]]


## Operações
## Indices, fatiamento(slices) e iteração

In [11]:
vetor_rand=np.random.randint(0,10,10)
# Seleção de intervalos
# Selecionando intervalo máximo excluindo valor no indice máximo
print("Selecionando limite superior:\n {}\n".format(vetor_rand[:5]))

# Selecionando intervalo com mínimo
print("Selecionando limite inferior: \n{}\n".format(vetor_rand[5:]))

# Selecionando uma faixa 
print("Selecionando uma intervalo: \n{}\n".format(vetor_rand[3:8]))

# Selecionando um passo de avanço
print("Avançando com passo 2: \n{}\n".format(vetor_rand[::2]))

# Inversão
print("Invertendo o vetor: \n{}\n".format(vetor_rand[:-1]))

Selecionando limite superior:
 [5 3 0 6 8]

Selecionando limite inferior: 
[0 5 6 8 9]

Selecionando uma intervalo: 
[6 8 0 5 6]

Avançando com passo 2: 
[5 0 8 5 8]

Invertendo o vetor: 
[5 3 0 6 8 0 5 6 8]



### Iterando sobre arrays

Para iterar sobre um array, pode-se utilizar qualquer um dos controles de fluxo disponíveis em python. **For**, **While**

In [12]:
# Iteração sobre vetores
for elemento in vetor:
    print(elemento)

1
2
3
4
5


In [13]:
# Iteração sobre matrizes
print('Imprimindo linhas')
for linha in matriz:
    print(linha)
    
print('Imprimindo elementos')
for linha in matriz:
    for elemento in linha:
        # imprimindo elementos em uma mesma linha
        print(elemento, end=' ')
    # inserindo uma quebra de linha
    print('\n')
    

Imprimindo linhas
[4 5 6]
[9 8 7]
Imprimindo elementos
4 5 6 

9 8 7 



### Usando iter
Uma outra forma para iteragir sobre estruturas é utilizando o a função [iter](https://docs.python.org/3.3/library/functions.html#iter)
iter transforma uma estrutura em um iterador (iterator). Dessa forma, o acesso ao elemento se faz através da função next. Veremos a seguir

In [14]:
# Iteração utilizando iter
iterador = iter(vetor)

print(next(iterador))
print(next(iterador))
print(next(iterador))


1
2
3


## Redimensionamento de arrays
Podemos utilizar operações para obter arrays similares aos arrays originais.

In [15]:
# Obtendo as formas
# Propriedades Tamanho e dimensões
print("Propriedades do vetor: Tamanho: {}, Dimensão{}".format(vetor.size, vetor.shape))
print("Propriedades da matriz: Tamanho: {}, Dimensão{}".format(matriz.size, matriz.shape))
print("Propriedades do tensor: Tamanho: {}, Dimensão{}".format(tensor.size, tensor.shape))

Propriedades do vetor: Tamanho: 5, Dimensão(5,)
Propriedades da matriz: Tamanho: 6, Dimensão(2, 3)
Propriedades do tensor: Tamanho: 9, Dimensão(3, 3)


### Planificação
É o procedimento para transformar matrizes e tensores em vetores. Ou seja, transformar arrays multidimensionais em arrays unidimensionais


In [16]:
# Planificando uma matriz ou tensor
print("Matriz planificada: \n {} \n".format(matriz.ravel()))
print("Tensor planificado: \n {} \n".format(tensor.ravel()))

Matriz planificada: 
 [4 5 6 9 8 7] 

Tensor planificado: 
 [1 2 3 4 5 6 7 8 9] 



### Transformação de dimensões

Podemos transformar arrays de uma dimensão $(m,n)$ de tal forma que o número sempre seja um divisor de $m*n$.

Quando se pretende transformar apenas uma das coordenadas, informamos o valor $(-1)$, a outra dimensão será calculada automaticamente

Dois métodos são utilizados para transformar as dimensões de um arrays **reshape** e **resize**

In [17]:
# Reshape, não modifica o array original, apenas retorna o novo formato
print("Modificando a forma da matriz \n{}\n".format(matriz.reshape(2,3)))
print("Matriz original \n{}\n".format(matriz))

Modificando a forma da matriz 
[[4 5 6]
 [9 8 7]]

Matriz original 
[[4 5 6]
 [9 8 7]]



In [18]:
# Resize modifica o array em si mesmo
print("Usando reshape, o retorno é None\n{}\n".format(matriz.resize((3,2))))
print("Mas a mudança foi feita na matriz em si\n{}\n ".format(matriz))

Usando reshape, o retorno é None
None

Mas a mudança foi feita na matriz em si
[[4 5]
 [6 9]
 [8 7]]
 


## Broadcasting ou propagação

Estes termos são utilizados para descrever como o NumPy trata operações aritméticas com arrays de formas diferentes. O array menor propaga sobre o maior, caso eles tenham dimensões compatíveis.


### Regras gerais de propagação

Quando for realizar operações com dois arrays, NumPy compara os as dimensões elemento a elemento. Começando pela dimensão mais ao final.
Duas dimensões são compatíveis quando

1. Elas são iguais, ou
2. Uma delas é 1

OU seja, exemplificando em termos de dimensões temos que a propagação funciona em sistemas com dimensões como no exmplo abaixo:
    5 x 1 e 1
    3 x 2 e 2
4 x 2 x 3 e 1
4 x 2 x 3 e 3
4 x 2 x 3 e 4 x 1 x 1
4 x 2 x 3 e 4 x 1 x 3

E por aí vai. Confuso não?! Nos exemplos espero deixar um pouco mais claro.

[Documentação aqui](https://docs.scipy.org/doc/numpy-1.10.1/user/basics.broadcasting.html)

[Ilustração dos conceitos de Broadcast(em inglês)](http://scipy.github.io/old-wiki/pages/EricsBroadcastingDoc)

In [19]:
# Exemplos de broadcast
np.random.randint(0,100,size=20).reshape(5,4)

array([[18, 50, 82, 57],
       [46, 58, 23, 21],
       [ 7, 81, 63,  0],
       [90, 44, 57, 14],
       [26, 43, 30, 99]])

### Transposição de matrizes

Transposição de uma matriz consiste em uma matriz espelho da original, através da diagonal principal. A transposta é obitida trocando-se a posição das linhas e colunas. Denota-se a tranposta da matriz **A** por $ A^T $


[Função transpose do Numpy](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.transpose.html)

In [20]:
print("Matriz \n {}".format(matriz))
print("Matriz Transposta \n {}".format(np.transpose(matriz)))

Matriz 
 [[4 5]
 [6 9]
 [8 7]]
Matriz Transposta 
 [[4 6 8]
 [5 9 7]]


In [21]:
print("Tensor \n {}".format(tensor))
print("Tensor Transposto, usando a forma simplificada \n {}".format(tensor.T))

Tensor 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Tensor Transposto, usando a forma simplificada 
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


## Operações com escalares

Para realizar operações com escalares, basta propagar o escalar pelo array, 
executando a operação com cada elemento do array e o escalar

$$ \begin{vmatrix} 1\ 2 \\ 3\ 4 \end{vmatrix} * 2 = \begin{vmatrix} 2\ 4 \\ 6\ 8 \end{vmatrix}$$


In [22]:
# Operação com escalares
# Aplica o conceito de propagação
print("Multiplicando o vetor por 3: \n{}\n".format(vetor * 3))
print("Somando 10 a matriz: \n {} \n".format(matriz + 10))
print("Dividindo o tensor por 5: \n {} \n".format(tensor / 5))

Multiplicando o vetor por 3: 
[ 3  6  9 12 15]

Somando 10 a matriz: 
 [[14 15]
 [16 19]
 [18 17]] 

Dividindo o tensor por 5: 
 [[0.2 0.4 0.6]
 [0.8 1.  1.2]
 [1.4 1.6 1.8]] 



### Soma e subtração 

Em álgebra, a soma de elementos de um array é feita realizando esta operação elemento a elemento ocupando a mesma posição em seus respectivos arrays. Por exemplo


$$\begin{vmatrix} 1\ 2 \\\ 3\ 4 \end{vmatrix}  + \begin{vmatrix} 5\ 6 \\\ 7\ 8 \end{vmatrix} = \begin{vmatrix} 6\ 8 \\\ 10\ 14 \end{vmatrix}$$

Em álgebra realizamos a soma de matrizes de mesma dimensões, mas no NumPy temos que lembrar que existe a propagação. Respeitando suas regras, existirá uma propagação das menores dimensões. 

In [23]:
# Usando arrays de mesmo tamanho
vetor1 = np.array([1,2,3,4,5])
vetor2 = np.array([6,3,2,7,8])

print(np.add(vetor1, vetor2))
print(vetor1 + vetor2)


[ 7  5  5 11 13]
[ 7  5  5 11 13]


In [24]:
print(np.subtract(vetor1, vetor2))
print(vetor1 - vetor2)

[-5 -1  1 -3 -3]
[-5 -1  1 -3 -3]


In [25]:
# Usando arrays de tamanhos diferentes
matriz1 = np.arange(10).reshape(2,5)
vetor_uns = np.ones(5)
matriz1 + vetor_uns

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

### Multiplicação de matrizes e vetores
Multiplicação de matrizes é algo que necessita de um pouco mais de manejo. Infelizmente não é tão direta como a soma, onde o requisito é que as dimensões sejam iguais. 

Os requisitos para multiplicação de matrizes é que o número de colunas da primeira matriz seja igual o número de linhas da segundo, ou seja, 
Seja uma matriz $A_{i,j}$ e uma matriz $B_{j,l}$, teremos como resultado da multiplicação uma matriz $C_{i,l}$, assim:
$$ A_{i,j} * B_{j,l} = C_{i,l} $$


In [26]:
# Usando arrays de mesmo tamanho
print(np.multiply(vetor1, vetor2.reshape(1,5)))
print(vetor1 * vetor2)
print(vetor2.reshape(1,-1))

[[ 6  6  6 28 40]]
[ 6  6  6 28 40]
[[6 3 2 7 8]]


In [27]:
print(np.divide(vetor1, vetor2))
print(vetor1 // vetor2)

[0.16666667 0.66666667 1.5        0.57142857 0.625     ]
[0 0 1 0 0]


### Matriz identidade

Matriz identidade é uma matriz que possui sua diagonal principal igual a 1 e os demais elementos igual a zero. Ou seja, é uma matriz que não altera nenhum vetor, quando for este for multiplicado por ela. O NumPy gera essa matriz através da função numpy.identity

[Matriz identidade](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.identity.html)

In [35]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

 ### Matriz inversa
 
 Matriz inveza, também denotada como $A^{-1}$ é a matriz que, ao multiplicar a matriz $A$, resulta em uma matriz identidade. 
 
Em NumPy, a matriz inversa pode ser obtida através da função [numpy.linalg.inv](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.linalg.inv.html)

In [42]:
m = np.array([3,5,6,1]).reshape(2,2)
np.linalg.inv(m)

array([[-0.03703704,  0.18518519],
       [ 0.22222222, -0.11111111]])

## Trabalhando com cópias e visões (views)

## Referências

### Em Português

1. https://pt.khanacademy.org/math/linear-algebra
2. https://www.youtube.com/watch?v=pbFZW1eTnkk

### Em Inglês

1. http://www.deeplearningbook.org/contents/linear_algebra.html
2. https://www.analyticsvidhya.com/blog/2017/05/comprehensive-guide-to-linear-algebra/
3. https://towardsdatascience.com/boost-your-data-sciences-skills-learn-linear-algebra-2c30fdd008cf
